name: build

on:
    push:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - name: Setup .NET Core
              uses: actions/setup-dotnet@v1
              with:
                dotnet-version: 7.0.201
            - name: Set env
              run: |
                echo "DOTNET_CLI_TELEMETRY_OPTOUT=1" >> $GITHUB_ENV
                echo "DOTNET_hostBuilder:reloadConfigOnChange=false" >> $GITHUB_ENV
            - name: Clean
              run: |
                dotnet clean ./SciSharp.MySQL.Replication.sln --configuration Release
                dotnet nuget locals all --clear
            - name: Build
              run: dotnet build -c Release
            - name: Run MySQL
              run: |
                cp tests/Test/mysql.cnf ~/.my.cnf
                sudo systemctl start mysql.service
                mysql -u root -p root garden < tests/Tesrt/dump.sql
            - name: Test
              run: |
                cd tests/Test
                dotnet test